export type OlitefQuestion = {
  id: number;
  level: "nivel-1" | "nivel-2";
  schoolYears?: string;
  macrotema: string;
  topic: string;
  subtema: string;
  skill: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  reasoningType: "conceitual" | "calculo" | "interpretacao";
  title: string;
  prompt: string;
  options: string[];
  answer: number;
  microLesson: string;
  hint: string;
  explanation: string;
  detailedExplanation: string;
  alternativeFeedback: string[];
  tags: string[];
  estimatedSeconds: number;
  video?: { title: string; id: string };
};

// ─── NÍVEL 1: 6.º e 7.º anos ────────────────────────────────────────────────
export const nivel1Questions: OlitefQuestion[] = [
  // ── Planejamento financeiro: Necessidades e desejos ──
  {
    id: 101, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Planejamento financeiro", topic: "Necessidades e desejos", subtema: "Escolhas de consumo", skill: "Distinguir necessidade de desejo", difficulty: 1, reasoningType: "conceitual", title: "Escolha com cabeça", prompt: "Qual item é uma necessidade para estudar?", options: ["Um caderno", "Um brinquedo novo", "Uma skin no jogo", "Um lanche extra"], answer: 0, microLesson: "Necessidade é algo importante para viver, estudar ou ter saúde. Desejo é algo que queremos, mas pode esperar.", hint: "Pense no item que ajuda diretamente na atividade de estudar.", explanation: "O caderno ajuda diretamente nos estudos. Os outros itens podem ser desejos: são legais, mas podem esperar.", detailedExplanation: "Comece perguntando: sem qual item a tarefa de estudar ficaria realmente prejudicada? O caderno é um material escolar. Já um brinquedo, uma skin e um lanche extra podem ser escolhidos depois, quando houver dinheiro e prioridade.", alternativeFeedback: ["Correta: o caderno é um material necessário para estudar.", "Pode ser um desejo, porque um brinquedo novo não é indispensável para a aula.", "Pode ser um desejo: a skin muda o jogo, mas não é necessária para estudar.", "Um lanche pode ser importante em alguns contextos, mas aqui a pergunta fala do material para estudar."], tags: ["prioridades", "consumo"], estimatedSeconds: 45, video: { title: "Educação financeira para crianças", id: "kJWYnzM9hpY" }
  },
  {
    id: 106, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Planejamento financeiro", topic: "Necessidades e desejos", subtema: "Classificação", skill: "Classificar gastos em necessidades e desejos", difficulty: 1, reasoningType: "conceitual", title: "O que é essencial?", prompt: "Qual das opções abaixo é mais uma necessidade do que um desejo?", options: ["Entrar num cinema", "Pagar a conta de luz", "Comprar um videogame", "Ir a uma festa"], answer: 1, microLesson: "A conta de luz é essencial para ter iluminação e funcionamento de equipamentos em casa.", hint: "Necessidade é algo sem o qual a vida fica muito difícil ou prejudicada.", explanation: "A luz em casa é essencial. Sem ela, não há estudo, nem geladeira, nem comunicação. As outras opções são desejos ou lazer.", detailedExplanation: "Pense na vida diária: sem luz, você não estuda à noite, não carrega o celular e não mantém a comida fresca. Já o cinema, o videogame e a festa são formas de entretenimento — importantes para o bem-estar, mas não essenciais para o funcionamento da casa.", alternativeFeedback: ["Cinema é lazer, não necessidade.", "Correta: luz é essencial para o funcionamento da casa e dos estudos.", "Videogame é um bem de lazer, não indispensável.", "Festa é entretenimento, não uma necessidade básica."], tags: ["necessidade", "desejo", "classificacao"], estimatedSeconds: 40
  },
  {
    id: 107, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Planejamento financeiro", topic: "Necessidades e desejos", subtema: "Priorização", skill: "Priorizar gastos conforme a importância", difficulty: 2, reasoningType: "interpretacao", title: "Ordem certa", prompt: "Se você tem R$ 100 e precisa pagar lanche da escola (R$ 30) e quer comprar um jogo (R$ 80), o que fazer primeiro?", options: ["Comprar o jogo", "Pagar o lanche e guardar o resto", "Comprar os dois no parcelamento", "Esperar o próximo mês"], answer: 1, microLesson: "Antes de querer, é preciso garantir o necessário. O lanche da escola é uma necessidade; o jogo é um desejo.", hint: "Sempre pague o que é necessário antes de pensar no que é desejo.", explanation: "Pagar o lanche (necessidade) e guardar o restante é a escolha mais inteligente. O jogo pode esperar até haver dinheiro sobrando.", detailedExplanation: "O lanche é uma necessidade: é o almoço do estudante. O jogo é um desejo que pode ser adiado. Ao pagar o necessário e guardar, você cria reserva para imprevistos e mantém o controle financeiro.", alternativeFeedback: ["O jogo custa mais do que o orçamento permite e não é essencial.", "Correta: priorize o necessário e guarde o que sobra.", "Parcelar o jogo pode gerar dívida por algo que não é essencial.", "Adiar tudo pode causar falta do almoço na escola."], tags: ["prioridades", "orcamento"], estimatedSeconds: 50
  },
  // ── Receitas e despesas ──
  {
    id: 102, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Planejamento financeiro", topic: "Receitas e despesas", subtema: "Saldo", skill: "Calcular o saldo de uma situação simples", difficulty: 2, reasoningType: "calculo", title: "O dinheiro em movimento", prompt: "Se entram R$ 30 e você gasta R$ 12, qual é o saldo?", options: ["R$ 18", "R$ 42", "R$ 12", "R$ 30"], answer: 0, microLesson: "Receita é o dinheiro que entra. Despesa é o dinheiro que sai. Saldo é o que sobra depois da conta.", hint: "Para descobrir o que sobra, faça o valor que entra menos o valor que sai.", explanation: "Saldo é o que sobra: R$ 30 − R$ 12 = R$ 18.", detailedExplanation: "Organize a conta em duas partes: receita de R$ 30 e despesa de R$ 12. Como a despesa sai do dinheiro disponível, subtraímos 12 de 30. O resultado é R$ 18, que pode ser guardado ou usado numa próxima decisão.", alternativeFeedback: ["Correta: R$ 30 − R$ 12 = R$ 18.", "Somar entrada e despesa mistura dinheiro que entrou com dinheiro que saiu.", "R$ 12 é a despesa, não o saldo final.", "R$ 30 é a receita inicial, antes de pagar a despesa."], tags: ["saldo", "subtracao"], estimatedSeconds: 50, video: { title: "Saving and Budgeting for Kids", id: "437hOqo4OVs" }
  },
  {
    id: 108, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Planejamento financeiro", topic: "Receitas e despesas", subtema: "Receita", skill: "Identificar fontes de renda", difficulty: 1, reasoningType: "conceitual", title: "De onde vem o dinheiro?", prompt: "Qual das opções abaixo é um exemplo de receita?", options: ["Pagar uma conta", "Receber mesada", "Comprar material escolar", "Gastar com transporte"], answer: 1, microLesson: "Receita é tudo o que entra de dinheiro. Mesada, salário, venda de algo são receitas.", hint: "Receita é quando o dinheiro vem para você.", explanation: "A mesada é dinheiro que entra — logo, é receita. Pagar, comprar e gastar são despesas (dinheiro que sai).", detailedExplanation: "Identificar receita e despesa é o primeiro passo para organizar as finanças. A mesada é uma receita fixa para o estudante. Já pagar contas, comprar materiais e pagar transporte são despesas porque o dinheiro sai do bolso.", alternativeFeedback: ["Pagar é despesa, não receita.", "Correta: mesada é dinheiro que entra, ou seja, receita.", "Comprar é uma despesa.", "Transporte gasta dinheiro, é despesa."], tags: ["receita", "despesa", "identificacao"], estimatedSeconds: 35
  },
  {
    id: 109, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Planejamento financeiro", topic: "Receitas e despesas", subtema: "Despesa fixa e variável", skill: "Distinguir despesa fixa de variável", difficulty: 2, reasoningType: "conceitual", title: "Fixo ou muda?", prompt: "Qual é um exemplo de despesa fixa?", options: ["Lanche da cantina", "Aluguel da casa", "Comprar roupas novas", "Ir ao cinema"], answer: 1, microLesson: "Despesa fixa é aquela que se repete todo mês com valor parecido. Despesa variável pode mudar de mês para mês.", hint: "Pense no gasto que acontece sempre igual, todo mês.", explanation: "O aluguel é fixo: é pago todo mês, geralmente o mesmo valor. Os outros exemplos variam conforme a escolha de cada mês.", detailedExplanation: "O aluguel é um compromisso mensal obrigatório e com valor previsível. Já o lanche, roupas e cinema dependem de escolhas pontuais — um mês pode gastar mais, outro menos. Distinguir fixo de variável ajuda a planejar o orçamento.", alternativeFeedback: ["Lanche pode variar de dia para dia.", "Correta: aluguel é uma despesa fixa mensal.", "Roupas são despesas variáveis — dependem de necessidade e desejo.", "Cinema é despesa variável, depende de escolha."], tags: ["despesa", "fixa", "variavel"], estimatedSeconds: 45
  },
  // ── Orçamento ──
  {
    id: 103, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Planejamento financeiro", topic: "Orçamento", subtema: "Organização do dinheiro", skill: "Organizar receitas e despesas antes de decidir", difficulty: 2, reasoningType: "interpretacao", title: "Faça o mapa", prompt: "Qual é a melhor ordem para organizar um orçamento?", options: ["Comprar e depois contar", "Anotar entradas, listar saídas e comparar", "Gastar tudo e pedir mais", "Escolher só pela promoção"], answer: 1, microLesson: "Orçamento é um mapa do dinheiro: mostra o que entra, o que sai e o que podemos guardar.", hint: "Um mapa é feito antes da viagem. O orçamento também deve vir antes da compra.", explanation: "Anote as receitas, liste as despesas e compare antes de decidir.", detailedExplanation: "Primeiro descubra quanto dinheiro está disponível. Depois, liste o que precisa pagar ou comprar. Só então compare as opções e decida o que cabe no orçamento. Assim, a promoção deixa de ser uma armadilha e vira apenas uma informação para comparar.", alternativeFeedback: ["Comprar antes de contar pode causar falta de dinheiro.", "Correta: entradas, saídas e comparação formam um orçamento simples.", "Gastar tudo elimina a possibilidade de planejar e guardar.", "Uma promoção só é boa se o produto for necessário e couber no orçamento."], tags: ["planejamento", "orcamento"], estimatedSeconds: 55, video: { title: "Saving and Budgeting for Kids", id: "437hOqo4OVs" }
  },
  {
    id: 110, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Planejamento financeiro", topic: "Orçamento", subtema: "Controle mensal", skill: "Elaborar um orçamento mensal simples", difficulty: 2, reasoningType: "calculo", title: "Conta do mês", prompt: "Se sua mesada é R$ 80 e você gasta R$ 20 em lanches e R$ 15 em transporte, quanto sobra?", options: ["R$ 35", "R$ 45", "R$ 55", "R$ 65"], answer: 1, microLesson: "Subtraia todas as despesas da receita para encontrar o que sobra no fim do mês.", hint: "Some as despesas e subtraia da mesada.", explanation: "R$ 80 − R$ 20 − R$ 15 = R$ 45.", detailedExplanation: "Primeiro some as despesas: R$ 20 + R$ 15 = R$ 35. Depois subtraia da mesada: R$ 80 − R$ 35 = R$ 45. Esse valor sobra para guardar ou usar em outro gasto planejado.", alternativeFeedback: ["Essa é a soma das despesas, não o saldo.", "Correta: R$ 80 − R$ 35 = R$ 45.", "Você somou apenas uma despesa.", "Esse valor excede o que sobra — verifique os cálculos."], tags: ["orcamento", "subtracao", "controle"], estimatedSeconds: 55
  },
  // ── Poupança ──
  {
    id: 104, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Planejamento financeiro", topic: "Poupança", subtema: "Metas", skill: "Dividir uma meta financeira pelo prazo", difficulty: 2, reasoningType: "calculo", title: "Meta em passos", prompt: "Para juntar R$ 60 em 6 semanas, quanto guardar por semana?", options: ["R$ 6", "R$ 8", "R$ 10", "R$ 12"], answer: 2, microLesson: "Uma meta fica mais fácil quando diz o que queremos, quanto custa e até quando queremos alcançar.", hint: "Divida o valor total pelo número de semanas.", explanation: "Dividimos a meta pelo prazo: R$ 60 ÷ 6 = R$ 10 por semana.", detailedExplanation: "A meta total é R$ 60 e o prazo tem 6 semanas. Como queremos parcelas iguais, dividimos 60 por 6. Guardar R$ 10 em cada semana completa exatamente os R$ 60 ao fim do prazo.", alternativeFeedback: ["R$ 6 por semana chegaria a apenas R$ 36.", "R$ 8 por semana chegaria a R$ 48, ainda abaixo da meta.", "Correta: R$ 60 ÷ 6 = R$ 10.", "R$ 12 por semana ultrapassaria a meta, mas não é o valor necessário para dividir igualmente."], tags: ["meta", "poupanca", "divisao"], estimatedSeconds: 55, video: { title: "A Árvore dos Sonhos — metas e poupança", id: "K82ISIhamAg" }
  },
  {
    id: 111, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Planejamento financeiro", topic: "Poupança", subtema: "Hábito de poupar", skill: "Reconhecer a importância de poupar regularmente", difficulty: 1, reasoningType: "conceitual", title: "Pequenos passos", prompt: "Qual é a melhor forma de começar a poupar?", options: ["Esperar sobrar muito dinheiro", "Guardar uma parte toda semana", "Pedir emprestado", "Investir tudo em ações"], answer: 1, microLesson: "Poupar é um hábito: pequeenas quantidades regulares podem formar uma boa reserva ao longo do tempo.", hint: "A consistência é mais importante que a quantidade.", explanation: "Guardar uma parte toda semana cria o hábito de poupar. Não precisa ser muito — o importante é a regularidade.", detailedExplanation: "Muitas pessoas pensam que só vale a pena poupar com valores grandes. Na verdade, pequenas quantidades, se guardadas com consistência, formam uma reserva significativa ao longo dos meses. Comece devagar e aumente quando puder.", alternativeFeedback: ["Esperar pode fazer com que o hábito nunca comece.", "Correta: guardar toda semana é o caminho para construir uma reserva.", "Pedir emprestado gera dívida, não reserva.", "Ações são investimentos de risco — não são o primeiro passo para poupar."], tags: ["poupanca", "habito"], estimatedSeconds: 40
  },
  {
    id: 112, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Planejamento financeiro", topic: "Poupança", subtema: "Juros simples", skill: "Calcular rendimento com juros simples", difficulty: 3, reasoningType: "calculo", title: "Dinheiro que cresce", prompt: "Se você guarda R$ 100 a uma taxa de 10% ao mês, quanto terá depois de 2 meses?", options: ["R$ 110", "R$ 120", "R$ 200", "R$ 210"], answer: 1, microLesson: "Juros simples são calculados sempre sobre o valor original. 10% de R$ 100 = R$ 10 por mês.", hint: "Calcule 10% do valor original e multiplique pelo número de meses.", explanation: "10% de R$ 100 = R$ 10. Em 2 meses: R$ 10 × 2 = R$ 20. Total: R$ 100 + R$ 20 = R$ 120.", detailedExplanation: "Com juros simples, o rendimento é sempre sobre o valor inicial. No 1.º mês: R$ 100 × 10% = R$ 10. No 2.º mês: novamente R$ 10. Total: R$ 120. Se fossem juros compostos, seria R$ 121 — mas juros simples não recaem sobre os juros já ganhos.", alternativeFeedback: ["R$ 110 é apenas 1 mês de rendimento.", "Correta: R$ 10 por mês × 2 = R$ 20 a mais, total R$ 120.", "R$ 200 seria o dobro, sem lógica de juros.", "R$ 210 seriam juros compostos de 2 meses, mas aqui são juros simples."], tags: ["juros", "poupanca", "calculo"], estimatedSeconds: 60
  },
  // ── Consumo consciente ──
  {
    id: 105, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Consumo consciente", topic: "Consumo consciente", subtema: "Compra por impulso", skill: "Avaliar uma compra antes de decidir", difficulty: 2, reasoningType: "interpretacao", title: "Pare e pense", prompt: "O que fazer antes de uma compra por impulso?", options: ["Comprar imediatamente", "Pedir a senha de alguém", "Esperar, comparar e perguntar se precisa", "Escolher o pacote maior sempre"], answer: 2, microLesson: "Consumo consciente é pensar antes de comprar: preciso, posso pagar e existe uma opção melhor?", hint: "Uma pausa de alguns minutos pode evitar uma decisão sem planejamento.", explanation: "Uma pausa ajuda a separar necessidade de desejo e comparar opções. Promoção não é economia se você não precisava comprar.", detailedExplanation: "Antes de comprar, faça três perguntas: eu preciso disso agora? posso pagar sem prejudicar uma meta? comparei preço e quantidade? Se a resposta for não, esperar é uma escolha inteligente, não uma perda de oportunidade.", alternativeFeedback: ["Comprar imediatamente é justamente o comportamento impulsivo que queremos evitar.", "Senhas são pessoais e nunca devem ser pedidas para realizar uma compra.", "Correta: pausar, comparar e avaliar a necessidade melhora a decisão.", "O pacote maior pode custar mais e não ser necessário; tamanho maior não significa automaticamente economia."], tags: ["consumo", "decisao", "seguranca"], estimatedSeconds: 50, video: { title: "Turma da Mônica — educação financeira", id: "K82ISIhamAg" }
  },
  {
    id: 113, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Consumo consciente", topic: "Consumo consciente", subtema: "Publicidade e propaganda", skill: "Identificar intenções da publicidade", difficulty: 2, reasoningType: "interpretacao", title: "Mensagem por trás", prompt: "Por que as empresas fazem propagandas com desconto e promoção?", options: ["Para ajudar os consumidores", "Para vender mais e aumentar o lucro", "Porque os produtos estão vencendo", "Por obrigação da lei"], answer: 1, microLesson: "Publicidade é uma ferramenta de venda. O objetivo é atrair compradores, não necessariamente oferecer a melhor oportunidade.", hint: "A propaganda tem um objetivo de negócio por trás.", explanation: "A propaganda existe para vender mais. Promoções podem ser reais, mas também podem ser estratégias para atrair clientes a comprarem mais do que precisam.", detailedExplanation: "Todo anúncio tem um objetivo de negócio: vender. Descontos e promoções são técnicas de marketing. Isso não significa que são fraudulentos, mas sim que o consumidor precisa ficar atento: um desconto em algo que você não precisa não é economia.", alternativeFeedback: ["Empresas ajudam, mas o objetivo principal é comercial.", "Correta: a propaganda visa vender mais e aumentar o lucro da empresa.", "Produtos vencidos não podem ser vendidos — é ilegal.", "A lei regula a publicidade, mas não obriga empresas a fazer propaganda."], tags: ["publicidade", "consumo", "critica"], estimatedSeconds: 50
  },
  {
    id: 114, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Consumo consciente", topic: "Consumo consciente", subtema: "Segurança financeira", skill: "Reconhecer riscos financeiros do cotidiano", difficulty: 2, reasoningType: "interpretacao", title: "Cuidado ao clicar", prompt: "Qual situação é um risco financeiro online?", options: ["Comprar num site oficial", "Divulgar dados bancários para um link desconhecido", "Usar cartão virtual em compras", "Verificar o saldo no app do banco"], answer: 1, microLesson: "Nunca compartilhe dados bancários por links, mensagens ou e-mails não verificados. Golpes financeiros são muito comuns na internet.", hint: "Pense em algo que colocaria seus dados em perigo.", explanation: "Divulgar dados bancários para links desconhecidos é um risco enorme. Golpistas usam isso para roubar dinheiro. Sites oficiais, apps do banco e cartões virtuais são ferramentas seguras quando usados corretamente.", detailedExplanation: "A internet trouxe conveniência, mas também riscos. Links falsos imitam sites reais para roubar senhas e dados bancários. Antes de clicar ou compartilhar informações, verifique se o site é oficial e se a mensagem veio de uma fonte confiável.", alternativeFeedback: ["Sites oficiais são geralmente seguros.", "Correta: divulgar dados para links desconhecidos é um risco grave de fraude.", "Cartões virtuais são uma camada extra de segurança.", "Verificar saldo no app é uma boa prática de controle financeiro."], tags: ["seguranca", "online", "golpes"], estimatedSeconds: 55
  },
  {
    id: 115, level: "nivel-1", schoolYears: "6.º e 7.º anos", macrotema: "Planejamento financeiro", topic: "Orçamento", subtema: "Classificação de gastos", skill: "Classificar gastos do dia a dia", difficulty: 1, reasoningType: "conceitual", title: "Onde vai o dinheiro?", prompt: "Qual é a melhor forma de anotar seus gastos do dia a dia?", options: ["Memorizar tudo", "Usar um caderno ou app de controle", "Perguntar aos pais", "Esquecer e comprar de novo"], answer: 1, microLesson: "Anotar gastos é o primeiro passo para controlar o orçamento. Pode ser no caderno, agenda ou aplicativo.", hint: "Pense em uma forma prática de registrar para não esquecer.", explanation: "Anotar os gastos (caderno ou app) ajuda a ver para onde o dinheiro vai e onde dá para economizar.", detailedExplanation: "Memorizar é arriscado — esquecemos detalhes. Usar um registro ajuda a criar consciência sobre os gastos, identificar padrões (como gastar demais com lanches) e planejar melhor o uso do dinheiro nos próximos meses.", alternativeFeedback: ["Memorizar faz você perder informações importantes.", "Correta: anotar é o melhor hábito para controle financeiro.", "Os pais podem ajudar, mas o controle pessoal é essencial.", "Esquecer os gastos pode gerar repetição dos mesmos erros."], tags: ["controle", "registro", "orcamento"], estimatedSeconds: 40
  },
];

// ─── NÍVEL 2: 8.º e 9.º anos ────────────────────────────────────────────────
export const nivel2Questions: OlitefQuestion[] = [
  // ── Finanças pessoais e endividamento ──
  {
    id: 201, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Finanças pessoais e endividamento", topic: "Crédito consciente", subtema: "Parcelamento", skill: "Calcular o custo real de uma compra parcelada", difficulty: 3, reasoningType: "calculo", title: "O preço real do parcelamento", prompt: "Um celular custa R$ 1.200 à vista ou em 12x de R$ 120. Qual o custo total do parcelamento?", options: ["R$ 1.200", "R$ 1.440", "R$ 1.080", "R$ 1.320"], answer: 1, microLesson: "Parcelamento sem juros mantém o preço. Com juros, o custo total aumenta. Sempre confirme se há juros na parcela.", hint: "Multiplique o valor da parcela pelo número de parcelas.", explanation: "12 × R$ 120 = R$ 1.440. Ou seja, o parcelamento com juros custa R$ 240 a mais que o pagamento à vista.", detailedExplanation: "Muitas vezes o parcelamento parece mais barato porque divide o valor. Mas se houver juros ocultos no preço da parcela (R$ 120 > R$ 100 que seria sem juros), o custo total é maior. Compare sempre: à vista R$ 1.200 vs. 12 × R$ 120 = R$ 1.440. A diferença de R$ 240 é o custo do crédito.", alternativeFeedback: ["Esse é o preço à vista, não o custo total do parcelamento.", "Correta: 12 × R$ 120 = R$ 1.440.", "Esse seria o valor sem juros (12 × R$ 90).", "Cálculo incorreto — verifique a multiplicação."], tags: ["credito", "parcelamento", "juros"], estimatedSeconds: 55
  },
  {
    id: 202, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Finanças pessoais e endividamento", topic: "Crédito consciente", subtema: "Endividamento", skill: "Reconhecer consequências do endividamento excessivo", difficulty: 2, reasoningType: "interpretacao", title: "Armadilha do cartão", prompt: "Qual é a consequência de parcelar muitas compras ao mesmo tempo no cartão de crédito?", options: ["Pagar mais barato", "Ficar com parcelas altas e comprometer o orçamento", "Ganhar mais dinheiro", "Melhorar o score de crédito"], answer: 1, microLesson: "Parcelar tudo gera varias parcelas simultâneas, que somam um valor alto no final do mês.", hint: "Pense em quantas parcelas terão que pagar no próximo boleto.", explanation: "Muitas parcelas ao mesmo tempo aumentam a conta mensal. Isso pode comprometer o orçamento e levar a atrasos, que geram multas e juros.", detailedExplanation: "O cartão de crédito pode ser útil, mas parcelar muitas coisas ao mesmo tempo cria uma \"bola de neve\": cada compra gera uma parcela, e todas chegam no mesmo mês. Se o orçamento não comporta, o cliente atrasa, paga multa e juros, e a dívida cresce. O ideal é parcelar com moderação e sempre considerar o comprometimento mensal.", alternativeFeedback: ["Parcelar geralmente custa mais, não menos.", "Correta: parcelar muitas coisas eleva as parcelas mensais e pode causar endividamento.", "Endividamento prejudica o score, não melhora.", "O score cai com atrasos, não sobe com parcelamento excessivo."], tags: ["endividamento", "cartao", "orcamento"], estimatedSeconds: 55
  },
  {
    id: 203, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Finanças pessoais e endividamento", topic: "Crédito consciente", subtema: "Juros", skill: "Calcular o efeito dos juros compostos", difficulty: 4, reasoningType: "calculo", title: "A bola de neve dos juros", prompt: "Se você deve R$ 500 e o juro é 5% ao mês (composto), quanto deve após 2 meses?", options: ["R$ 525", "R$ 550", "R$ 551,25", "R$ 600"], answer: 2, microLesson: "Juros compostos incidem sobre o valor já acrescido de juros do mês anterior. É a \"bola de neve\" das finanças.", hint: "No 1.º mês calcule 5% de R$ 500 e some. No 2.º mês, calcule 5% do novo valor.", explanation: "1.º mês: R$ 500 × 5% = R$ 25 → R$ 525. 2.º mês: R$ 525 × 5% = R$ 26,25 → R$ 551,25.", detailedExplanation: "Juros compostos incidem sobre o valor acumulado, não sobre o valor original. No 1.º mês, os juros são R$ 25 (5% de R$ 500). No 2.º mês, os juros são R$ 26,25 (5% de R$ 525). Total: R$ 551,25. Se fossem juros simples, seriam R$ 550 (R$ 25 × 2). A diferença parece pequena em valores baixos, mas cresce muito com o tempo — por isso as dívidas de cartão de crédito crescem tão rápido.", alternativeFeedback: ["R$ 525 é apenas 1 mês de juros.", "R$ 550 seriam juros simples, não compostos.", "Correta: 5% de R$ 525 = R$ 26,25 → R$ 551,25.", "Esse valor seria o dobro — muito acima do esperado."], tags: ["juros", "compostos", "divida"], estimatedSeconds: 65
  },
  {
    id: 204, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Finanças pessoais e endividamento", topic: "Crédito consciente", subtema: "Types of credit", skill: "Distinguir tipos de crédito disponíveis", difficulty: 2, reasoningType: "conceitual", title: "Qual crédito usar?", prompt: "Qual é a diferença principal entre um empréstimo bancário e o cartão de crédito?", options: ["Não há diferença", "Empréstimo tem prazo definido; cartão é revolving", "Cartão tem juros menores", "Empréstimo não precisa devolver"], answer: 1, microLesson: "Empréstimo bancário: valor único, parcelas fixas, prazo definido. Cartão de crédito: rotativo, com juros altíssimos se não pagar à vista.", hint: "Pense na forma como cada um cobra juros e como o pagamento é organizado.", explanation: "Empréstimo bancário tem parcelas fixas e prazo definido, o que facilita planejar. Cartão de crédito é rotativo — se não pagar tudo, os juros incidem sobre o saldo devedor mensalmente.", detailedExplanation: "O empréstimo é mais transparente: você sabe exatamente quanto vai pagar e por quanto tempo. O cartão de crédito, se não for pago integralmente, vira crédito rotativo com juros que podem chegar a 400% ao ano. Entender essa diferença é essencial para não cair em armadilhas financeiras.", alternativeFeedback: ["Há diferenças fundamentais entre os dois.", "Correta: empréstimo parcelado fixo vs. cartão rotativo com juros altos.", "Cartão à vista pode não ter juros, mas o rotativo tem juros muito altos.", "Todo empréstimo precisa ser devolvido com juros."], tags: ["credito", "tipos", "emprestimo"], estimatedSeconds: 55
  },
  // ── Produtos de renda fixa ──
  {
    id: 205, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Produtos de renda fixa", topic: "Poupança e renda fixa", subtema: "Tesouro Direto", skill: "Identificar características do Tesouro Direto", difficulty: 2, reasoningType: "conceitual", title: "Investimento seguro", prompt: "Qual é uma característica do Tesouro Direto?", options: ["Risco alto e retorno garantido", "Governo garante o investimento, com baixo risco", "Só serve para milionários", "O valor pode cair pela metade"], answer: 1, microLesson: "O Tesouro Direto é um investimento do governo brasileiro. É considerado um dos mais seguros, pois o governo garante o pagamento.", hint: "Pense em quem está por trás desse investimento: o governo federal.", explanation: "O Tesouro Direto é garantido pelo governo federal, o que o torna um dos investimentos mais seguros. Renda fixa significa que você sabe quanto vai receber no final.", detailedExplanation: "O Tesouro Direto permite investir em títulos públicos (como Tesouro Selic, IPCA+ e Prefixado). Como o governo é o devedor, o risco de não receber é extremamente baixo. É acessível (a partir de R$ 30) e pode ser usado como primeira experiência de investimento.", alternativeFeedback: ["Investimentos seguros têm retorno mais moderado, não alto.", "Correta: o governo garante, com baixo risco e retorno previsível.", "O mínimo é R$ 30 — acessível para todos.", "Em renda fixa, o retorno é previsível, não imprevisível."], tags: ["investimento", "renda_fixa", "tesouro"], estimatedSeconds: 55
  },
  {
    id: 206, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Produtos de renda fixa", topic: "Poupança e renda fixa", subtema: "CDB e liquidez", skill: "Diferenciar liquidez diária de liquidez no vencimento", difficulty: 3, reasoningType: "conceitual", title: "Quando posso resgatar?", prompt: "O que significa \"liquidez\" num investimento?", options: ["Quanto dinheiro está investido", "Facilidade de resgatar o dinheiro investido", "A taxa de juros paga", "O tempo mínimo do investimento"], answer: 1, microLesson: "Liquidez é a facilidade de transformar o investimento em dinheiro disponível. Alta liquidez = pode resgatar a qualquer momento.", hint: "Pense em poder usar o dinheiro investido rapidamente.", explanation: "Liquidez é a capacidade de resgatar o investimento sem perdas significativas. Um investimento de alta liquidez permite sacar o dinheiro a qualquer momento.", detailedExplanation: "Investimentos com liquidez diária (como o Tesouro Selic) permitem resgatar o dinheiro a qualquer momento. Outros (como CDB de prazo fixo) só permitem resgate no vencimento. Entender a liquidez ajuda a escolher o investimento certo para cada necessidade: reserva de emergência precisa de alta liquidez; objetivo de longo prazo pode ter liquidez menor.", alternativeFeedback: ["Esse é o capital investido, não a liquidez.", "Correta: liquidez é a facilidade de resgatar o dinheiro.", "A taxa de juros é o rendimento, não a liquidez.", "O prazo mínimo afeta a liquidez, mas não é o que define o termo."], tags: ["renda_fixa", "liquidez", "investimento"], estimatedSeconds: 55
  },
  {
    id: 207, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Produtos de renda fixa", topic: "Poupança e renda fixa", subtema: "Renda fixa vs. poupança", skill: "Comparar rendimento da poupança com outros investimentos", difficulty: 3, reasoningType: "calculo", title: "Rende mais ou menos?", prompt: "Se a poupança rende 0,5% ao mês e o Tesouro Selic rende 1% ao mês, quanto a mais você ganha em 6 meses com R$ 1.000 no Tesouro Selic?", options: ["R$ 10", "R$ 30", "R$ 60", "R$ 120"], answer: 1, microLesson: "Poupança: R$ 1.000 × 0,5% × 6 = R$ 30. Tesouro Selic: R$ 1.000 × 1% × 6 = R$ 60. Diferença: R$ 30 a mais.", hint: "Calcule o rendimento de cada um e subtraia.", explanation: "Poupança: R$ 30. Selic: R$ 60. Diferença: R$ 30. O Tesouro Selic rendeu o dobro neste exemplo.", detailedExplanation: "A poupança historicamente rende abaixo do Tesouro Selic. Em 6 meses: poupança = R$ 30; Selic = R$ 60. A diferença de R$ 30 parece pequena, mas em valores maiores e prazos mais longos, essa diferença se torna significativa. Investir em renda fixa com melhor rendimento pode ser uma forma eficaz de proteger o poder de compra do dinheiro.", alternativeFeedback: ["Esse é o rendimento da poupança em 6 meses.", "Correta: R$ 60 (Selic) − R$ 30 (poupança) = R$ 30 a mais.", "Esse seria o rendimento total do Selic, não a diferença.", "Esse seria o rendimento anual de um investimento com juros compostos."], tags: ["poupanca", "renda_fixa", "comparacao"], estimatedSeconds: 60
  },
  // ── Introdução à renda variável ──
  {
    id: 208, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Introdução à renda variável", topic: "Renda variável", subtema: "Ações", skill: "Entender o conceito básico de ações", difficulty: 2, reasoningType: "conceitual", title: "Ser dono de uma empresa", prompt: "Quando você compra uma ação, o que está fazendo?", options: ["Emprestando dinheiro ao governo", "Comprando uma parte da empresa", "Depositando numa poupança", "Pagando um imposto"], answer: 1, microLesson: "Ação é um pedacinho de uma empresa. Quem compra ações torna-se sócio (dono parcial) daquela empresa.", hint: "Pense em dividir uma pizza: cada pedaço é uma parte do todo.", explanation: "Comprar ações é comprar uma parte da empresa. Se a empresa crescer, o valor da sua parte pode aumentar. Se cair, pode perder dinheiro.", detailedExplanation: "Ações representam frações do capital de uma empresa listada em bolsa. Quando você compra uma ação, torna-se sócio. O preço da ação varia conforme o desempenho da empresa, expectativas do mercado e fatores econômicos. Por isso, é investimento de renda variável: o retorno não é garantido.", alternativeFeedback: ["Investir no governo é renda fixa (Tesouro Direto), não ações.", "Correta: ação = pedacinho de empresa = sócio parcial.", "Ação não é poupança — o retorno não é garantido.", "Ações não são impostos — imposto é cobrado sobre o ganho, se houver."], tags: ["renda_variavel", "acoes", "investimento"], estimatedSeconds: 50
  },
  {
    id: 209, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Introdução à renda variável", topic: "Renda variável", subtema: "Risco e retorno", skill: "Relacionar risco e retorno em investimentos", difficulty: 2, reasoningType: "conceitual", title: "Alto risco, alto retorno?", prompt: "Qual é a relação entre risco e retorno nos investimentos?", options: ["Quanto menor o risco, maior o retorno", "Quanto maior o risco, maior o retorno potencial", "Risco e retorno não se influenciam", "Investimentos seguros rendem mais"], answer: 1, microLesson: "Investimentos mais arriscados podem render mais, mas também podem causar mais perdas. Investimentos seguros rendem menos, mas com mais previsibilidade.", hint: "Pense numa montanha-russa: quanto mais alta, mais emoção — e mais chance de queda.", explanation: "Existe uma relação direta: investimentos mais arriscados oferecem retorno potencial maior, mas também maior chance de perda.", detailedExplanation: "No mercado financeiro, não existe retorno alto sem risco. Ações podem render muito ou podem cair. Renda fixa (como Tesouro Direto) rende menos, mas é mais previsível. O ideal é diversificar: parte em investimentos seguros, parte em investimentos com mais potencial, conforme o perfil e o prazo do investidor.", alternativeFeedback: ["Geralmente é o oposto: risco alto = retorno potencial alto.", "Correta: há uma relação direta entre risco e retorno potencial.", "Risco e retorno estão diretamente relacionados.", "Investimentos seguros rendem menos, não mais — por isso são seguros."], tags: ["risco", "retorno", "investimento"], estimatedSeconds: 50
  },
  {
    id: 210, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Introdução à renda variável", topic: "Renda variável", subtema: "Diversificação", skill: "Aplicar o princípio da diversificação", difficulty: 3, reasoningType: "interpretacao", title: "Não coloque tudo no mesmo cesto", prompt: "Por que é recomendável diversificar investimentos?", options: ["Para ganhar mais dinheiro imediatamente", "Para reduzir o risco de perder tudo", "Porque é obrigação da lei", "Para pagar menos impostos"], answer: 1, microLesson: "Diversificar é espalhar o dinheiro entre diferentes investimentos. Se um cair, os outros podem compensar a perda.", hint: "Pense em não colocar todos os ovos na mesma cesta.", explanation: "Diversificar reduz o risco: se um investimento render mal, os outros podem compensar. É uma estratégia de proteção.", detailedExplanation: "A regra mais antiga dos investimentos é: não coloque todos os ovos na mesma cesta. Se você investe tudo numa única empresa e ela quebra, perde tudo. Mas se divide entre renda fixa, ações de empresas diferentes e outros tipos, a perda de um é compensada pelo ganho do outro. Diversificação não elimina o risco, mas o distribui.", alternativeFeedback: ["Diversificar não garante ganho imediato — é estratégia de longo prazo.", "Correta: diversificar espalha o risco e protege contra perdas grandes.", "Não é obrigação legal — é uma recomendação de boa prática.", "Diversificar não reduz impostos diretamente."], tags: ["diversificacao", "risco", "estrategia"], estimatedSeconds: 55
  },
  // �─ Economia e câmbio ──
  {
    id: 211, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Economia e câmbio", topic: "Câmbio e economia", subtema: "Câmbio", skill: "Calcular uma conversão de moeda simples", difficulty: 3, reasoningType: "calculo", title: "Moeda estrangeira", prompt: "Se 1 dólar = R$ 5,00 e você quer comprar algo de US$ 30, quanto custa em reais?", options: ["R$ 30", "R$ 100", "R$ 150", "R$ 500"], answer: 2, microLesson: "Para converter dólar para real, multiplique o valor em dólar pela cotação (preço do dólar em reais).", hint: "Multiplique: US$ 30 × R$ 5,00", explanation: "US$ 30 × R$ 5,00 = R$ 150. O item custa R$ 150 no Brasil.", detailedExplanation: "A cotação do dólar indica quantos reais valem um dólar. Para converter, basta multiplicar. Se o dólar sobe (valorização), o produto fica mais caro em reais. Se desce, fica mais barato. Essa variação afeta diretamente o preço de produtos importados no Brasil.", alternativeFeedback: ["Esse é o valor sem conversão.", "Esse seria US$ 20 × R$ 5.", "Correta: US$ 30 × R$ 5 = R$ 150.", "Esse seria US$ 100 × R$ 5."], tags: ["cambio", "conversao", "moeda"], estimatedSeconds: 50
  },
  {
    id: 212, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Economia e câmbio", topic: "Câmbio e economia", subtema: "Inflação", skill: "Compreender o efeito da inflação no poder de compra", difficulty: 3, reasoningType: "interpretacao", title: "Preços sobem, poder de compra cai", prompt: "Se a inflação é de 10% ao ano e seu salário não aumenta, o que acontece com seu poder de compra?", options: ["Aumenta", "Diminui", "Fica igual", "Depende do banco"], answer: 1, microLesson: "Inflação é a alta geral dos preços. Se os preços sobem e o salário fica igual, você compra menos com o mesmo dinheiro.", hint: "Pense em poder de compra: quantos produtos dá para comprar com o mesmo valor.", explanation: "Com inflação de 10%, tudo fica 10% mais caro. Se o salário não aumenta, o poder de compra diminui — você compra menos com o mesmo dinheiro.", detailedExplanation: "A inflação corrói o valor do dinheiro ao longo do tempo. Se antes R$ 100 comprava 10 kg de arroz, com inflação de 10%, agora compra apenas 9 kg. Para manter o poder de compra, o salário precisa acompanhar (ou superar) a inflação. Esse conceito é essencial para entender por que investir é importante: manter o dinheiro parado é perder poder de compra.", alternativeFeedback: ["O poder de compra só aumenta se o salário cresce mais que a inflação.", "Correta: a inflação reduz o poder de compra quando o salário não acompanha.", "Fica pior, não igual — os preços aumentaram.", "A inflação afeta a todos, independentemente do banco."], tags: ["inflacao", "poder_de_compra", "economia"], estimatedSeconds: 55
  },
  {
    id: 213, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Economia e câmbio", topic: "Câmbio e economia", subtema: "Oferta e procura", skill: "Relacionar oferta e procura com a formação de preços", difficulty: 2, reasoningType: "interpretacao", title: "Lei básica do mercado", prompt: "Se um produto está muito escasso (pouco disponível) e todos querem comprar, o que acontece com o preço?", options: ["Diminui", "Aumenta", "Fica igual", "Depende do governo"], answer: 1, microLesson: "Lei básica da oferta e procura: pouca oferta + muita procura = preço alto. Muita oferta + pouca procura = preço baixo.", hint: "Pense no que acontece com o preço de um produto que acaba rápido.", explanation: "Quando a oferta é baixa e a procura é alta, o vendedor pode cobrar mais caro porque as pessoas estão dispostas a pagar mais para conseguir o produto.", detailedExplanation: "A formação de preços no mercado é influenciada pela relação entre oferta (quantidade disponível) e procura (quantidade que as pessoas querem). Quando um produto está em falta e todos querem, o preço sobe. Quando há muita oferta e pouca demanda, os vendedores baixam o preço para vender. Esse mecanismo é a base da economia de mercado.", alternativeFeedback: ["Preço só cai quando há muita oferta ou pouca procura.", "Correta: pouca oferta + muita procura = preço alto.", "O preço pode subir mesmo sem intervenção do governo.", "Não depende — é lei natural do mercado."], tags: ["oferta", "procura", "preco"], estimatedSeconds: 50
  },
  {
    id: 214, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Finanças pessoais e endividamento", topic: "Crédito consciente", subtema: " score de crédito", skill: "Entender o conceito de score de crédito", difficulty: 2, reasoningType: "conceitual", title: "Sua reputação financeira", prompt: "O que é o score de crédito?", options: ["A quantidade de dinheiro que você tem", "Uma nota que indica seu histórico de pagamento", "O valor do seu salário", "O número de cartões que você possui"], answer: 1, microLesson: "Score é um número (0 a 1000) que resume seu histórico financeiro: pagou em dia, tem dívidas, usa crédito com moderação.", hint: "Pense numa nota que diz se você é um bom pagador.", explanation: "O score reflete seu histórico de pagamentos. Quanto maior, mais confiável você é para o mercado financeiro.", detailedExplanation: "O score é uma pontuação de 0 a 1000 gerada por bureaus de crédito (como Serasa). Quanto maior, maior a chance de conseguir crédito com boas condições. Ele considera: pontualidade de pagamentos, quantas dívidas existem, tempo de relacionamento com bancos e frequência de consultas de crédito. Manter o score alto abre portas para empréstimos, financiamentos e até aluguéis.", alternativeFeedback: ["O score não mede quanto dinheiro você tem, mas como você gerencia.", "Correta: score = nota baseada no histórico de pagamentos.", "Salário não entra diretamente no cálculo do score.", "Ter muitos cartões sem disciplina pode baixar o score."], tags: ["score", "credito", "historico"], estimatedSeconds: 50
  },
  {
    id: 215, level: "nivel-2", schoolYears: "8.º e 9.º anos", macrotema: "Produtos de renda fixa", topic: "Poupança e renda fixa", subtema: "CDB", skill: "Entender o funcionamento de um CDB", difficulty: 2, reasoningType: "conceitual", title: "O banco me paga por guardar dinheiro", prompt: "O que é um CDB (Certificado de Depósito Bancário)?", options: ["Um tipo de empréstimo que o banco faz para você", "Um investimento onde você empresta dinheiro ao banco e recebe juros", "Uma conta corrente comum", "Um cartão de crédito especial"], answer: 1, microLesson: "No CDB, você \"empresta\" dinheiro ao banco por um tempo e o banco paga juros sobre esse valor.", hint: "Pense em guardar dinheiro no banco e receber por isso.", explanation: "No CDB, o investidor deposita dinheiro no banco por um prazo e recebe juros ao final. É renda fixa e pode ter liquidez diária ou no vencimento.", detailedExplanation: "O CDB é um dos investimentos de renda fixa mais conhecidos. O banco precisa de dinheiro para emprestar a outros clientes, então oferece o CDB: investidor aplica, banco usa o dinheiro e paga juros. É garantido pelo FGC (Fundo Garantidor de Créditos) até R$ 250 mil por instituição. Pode ter liquidez diária (pode sacar a qualquer momento) ou no vencimento (só saca no fim do prazo).", alternativeFeedback: ["No CDB, o banco é quem recebe o empréstimo (do investidor).", "Correta: você empresta ao banco e recebe juros em troca.", "CDB é investimento, não conta corrente.", "CDB é investimento, não produto de crédito."], tags: ["cdb", "renda_fixa", "investimento"], estimatedSeconds: 55
  },
];

export const allOlitefQuestions = [...nivel1Questions, ...nivel2Questions];
